#!/bin/bash

set -eu

day="$(printf "%02d" "$1")"
sep() {
  printf '================\n'
}

# Make it harder to delete or change these.
chmod 400 input/*

if [ -e zig/${day}.zig ]; then
  sep
  (set -x; zig test zig/${day}.zig)
fi

sol=solutions/${day}.txt
if [ -f "${sol}" ]; then
  sep
  (set -x; cat ${sol})
  if [ "$(stat -f %p ${sol})" -ne 100400 ]; then
    printf '!!! WARNING !!! %s is not write protected!\n' ${sol}
  fi
fi

for input in input/${day}*; do
  if [ -e rb/${day}.rb ]; then
    sep
    (set -x; ruby rb/${day}.rb ${input})
  fi
  if [ -e zig/${day}.zig ]; then
    sep
    (set -x; zig run zig/${day}.zig -- ${input})
  fi
done
